# Generated by Django 6.0.1 on 2026-01-24 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 24, 12, 11, 56, 797217, tzinfo=datetime.timezone.utc)),
        ),
    ]
