# Generated by Django 6.0.1 on 2026-01-31 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='category_id',
            new_name='category',
        ),
    ]
