# Generated by Django 6.0.1 on 2026-01-27 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_title_category_name_alter_news_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 27, 8, 59, 57, 141333, tzinfo=datetime.timezone.utc)),
        ),
    ]
